### PR TITLE
quick and simple BeatSynthConverter integration

### PR DESCRIPTION
**Pull request by tommaier123**
This is a quick and simple BeatSynthConverter integration. I will add a way to change the settings later. Also I really should be using the already existing classes but that will be a bit more work.

### CODE REVIEW

**Comment by Zeks** [comment]
Are dlls supposed to come with commits? I think .gitignore file needs updating

**Comment by tommaier123** [comment]
> 
> 
> Are dlls supposed to come with commits? I think .gitignore file needs updating

Pretty sure some of the dependencies use dll libraries so they cant be excluded.

**Comment by tommaier123** [comment]
I have made a update to use the internal classes and I have also fixed a bug that happened when trying to convert a audio file that already existed.

**Comment by shogoki-vnz** [comment]
Hi @tommaier123 it appears you also upload the build files:

- SynthRiders Editor_Data	
- SynthRiders Editor.exe	
- UnityCrashHandler64.exe
- UnityPlayer.dll
- WinPixEventRuntime.dll
- Mono

can you remove the files before doing the merge?

**Comment by shogoki-vnz** [comment]
BeatSynthConverter integration

**Pull request merged**
